server:
  port: ${PORT:${SERVER_PORT:9094}}

spring:
  application:
    name: project
  devtools:
    add-properties: false
  main:
    allow-bean-definition-overriding: true
    banner-mode: "off"

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://34.226.199.170:5432/postgres
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      properties:
        hibernate.default_schema: customSchema
